### PR TITLE
add non-discrimination and anti-harassment policy

### PR DESCRIPTION
**Pull request by hazeltorek**
draft pull request to add the university's non-discrimination and anti-harassment policy, as this is required by csle. will also be addressing typos and making small changes to bring it up to date

### CODE REVIEW

**Comment by hazeltorek** [comment]
here's the current build. please review thoroughly and let me know if there's anything that needs to be changed
[constitution_bylaws.pdf](https://github.com/user-attachments/files/17152143/constitution_bylaws.pdf)

**Comment by Stine-F** [comment]
I think most of the instances that mention Clemson University and students and need to be changed to specify that this policy applies to the chapter and organization members.

**Comment by hazeltorek** [comment]
i believe we are supposed to include the policy in its entirety without editing the content, since this states that just merging the pdfs would be suitable as well: 

image

this is from the csle inactive organization re-registration form

**Comment by Stine-F** [comment]
Oh, Then everything looks good.

**Review by Stine-F — COMMENTED** [review]
Looks all good!

**Comment by Quantiset** [comment]
Looks great!

**Review by Quantiset — APPROVED** [review]
Looks great!

**Review by coolguycaden — APPROVED** [review]
Seems good, I have some personal questions we can talk about some other time.

**Comment by kfullero** [comment]
Looks good :)

**Review by kfullero — COMMENTED** [review]
looks good

**Pull request closed without merging**
